name: Build, Push to ACR, and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myacr003.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t myacr003.azurecr.io/helloworld:latest .
          docker push myacr003.azurecr.io/helloworld:latest

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.2

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Set up kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Deploy with Helm
        run: |
          helm upgrade --install helloworld ./helm/helloworld --set image.repository=myacr003.azurecr.io/helloworld --set image.tag=latest --namespace default
